#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
wmname LG3D &
sxhkd &
nm-applet &
blueman-applet &
xrandr --output eDP-1 --mode 2736x1824 --pos 207x1080 --scale 0.55x0.55 &
$HOME/.config/polybar/launch.sh &
xrandr --output HDMI-1 --mode 1920x1080 --pos 0x0 &
betterlockscreen -u ~/Pictures/wallpapers/red.png &
feh --bg-fill ~/Pictures/wallpapers/red.png &
picom &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor eDP-1 -d I II III IV V
bspc monitor HDMI-1 -d I II III IV V

bspc config right_padding        0
bspc config bottom_padding       0
bspc config border_width         5
bspc config active_border_color '#33b4de'
bspc config normal_border_color '#ADD8E6'
bspc config focused_border_color '#33b4de'
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^5'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
